package com.payroll.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * ============================================================================
 * Standardized REST Generic API Response Envelope
 * ============================================================================
 * 
 * Why This Class Exists:
 * --------------------
 * Ensures consistent JSON response structure across all REST API endpoints.
 * Wraps status, message, timestamp, and generic payload `T`.
 * 
 * OOP Concepts Used:
 * --------------------
 * - Generics (Type Abstraction): {@code <T>} enables type-safe response payload wrapping.
 * - Encapsulation: Private data fields with getters/setters via Lombok annotations.
 * - Static Factory Methods: {@code success()} and {@code error()} encapsulate object instantiation logic.
 * 
 * Design Patterns Used:
 * --------------------
 * - Generic API Response Envelope Pattern.
 * - Builder Pattern: Generated by Lombok {@code @Builder}.
 * - Static Factory Method Pattern: Provides clean static instantiation shortcuts.
 * 
 * @param <T> Payload data type
 * @author Senior Java Software Architect
 * @version 1.0.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ApiResponse<T> {

    /** HTTP response status code (e.g., 200, 201, 400, 404, 500). */
    private int status;

    /** Human-readable status description or error message. */
    private String message;

    /** Generic response data payload. */
    private T data;

    /** Timestamp when the response was generated. */
    @Builder.Default
    private LocalDateTime timestamp = LocalDateTime.now();

    /**
     * Creates a success response wrapper with payload data.
     *
     * @param status  HTTP status code
     * @param message Outcome message
     * @param data    Response payload
     * @param <T>     Payload type
     * @return Formatted {@link ApiResponse} object
     */
    public static <T> ApiResponse<T> success(final int status, final String message, final T data) {
        return ApiResponse.<T>builder()
                .status(status)
                .message(message)
                .data(data)
                .timestamp(LocalDateTime.now())
                .build();
    }

    /**
     * Creates a success response wrapper without payload data.
     *
     * @param status  HTTP status code
     * @param message Outcome message
     * @param <T>     Payload type
     * @return Formatted {@link ApiResponse} object
     */
    public static <T> ApiResponse<T> success(final int status, final String message) {
        return success(status, message, null);
    }

    /**
     * Creates an error response wrapper with detail payload.
     *
     * @param status  HTTP status code
     * @param message Error description
     * @param data    Error details payload (e.g. map of validation field errors)
     * @param <T>     Payload type
     * @return Formatted {@link ApiResponse} object
     */
    public static <T> ApiResponse<T> error(final int status, final String message, final T data) {
        return ApiResponse.<T>builder()
                .status(status)
                .message(message)
                .data(data)
                .timestamp(LocalDateTime.now())
                .build();
    }

    /**
     * Creates an error response wrapper without details payload.
     *
     * @param status  HTTP status code
     * @param message Error description
     * @param <T>     Payload type
     * @return Formatted {@link ApiResponse} object
     */
    public static <T> ApiResponse<T> error(final int status, final String message) {
        return error(status, message, null);
    }
}
